version: '3.8'

services:
  redis:
    image: redis/redis-stack:7.4.0-v2
    container_name: entrained-ai-engram-redis
    ports:
      - "6379:6379"
      - "8002:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-stack-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - engram-network

  engram:
    build: .
    container_name: entrained-ai-engram-api
    ports:
      - "8000:8000"
    environment:
      - ENGRAM_REDIS_HOST=redis
      - ENGRAM_REDIS_PORT=6379
      - ENGRAM_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - ENGRAM_DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - engram-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:

networks:
  engram-network:
    driver: bridge
    name: entrained-ai-engram-network